menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}

social:
- {icon: 'github', link: 'https://github.com/gabriel-lipkowitz'}
- {icon: 'twitter', link: 'https://twitter.com/gabriellipkowi2'}

contacts:
- {name: 'Gabriel Lipkowitz', title: 'PhD Student', department: 'Mechanical Engineering', institution: 'Stanford University', institution_address: '318 Campus Drive, Stanford, CA', email: 'gel19@stanford.edu', office: 'James H. Clark Center', image: 'assets/img/profile.jpeg'}
